
-- =============================================================
-- Snowflake Backup Setup & Operations Script
-- Author: Generated by M365 Copilot for Chetan Surti
-- Date: 2026-01-06
-- Purpose: Create role, database, schema, warehouse; grant privileges;
--          define backup policies; create/alter backup sets; and restore.
-- Notes:
--  * Adjust variable values below as needed before running.
--  * Some features (e.g., retention lock) require Business Critical Edition or higher.
--  * Run sections in order for best results.
-- =============================================================

-- ===============================
-- 1) Set variables (edit as needed)
-- ===============================
SET database_name  = 'BACKUP_DB';
SET schema_name    = 'BACKUP_SCM';
SET role_name      = 'BACKUP_ROLE';
SET warehouse_name = 'BACKUP_WH';

-- capture current user to grant the role later
SET current_username = (SELECT CURRENT_USER());

-- ===============================
-- 2) Create role and assign
-- ===============================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS IDENTIFIER($role_name);

-- grant to current user
GRANT ROLE IDENTIFIER($role_name) TO USER IDENTIFIER($current_username);

-- grant to SYSADMIN (so SYSADMIN can switch into it if needed)
GRANT ROLE IDENTIFIER($role_name) TO ROLE SYSADMIN;

-- ===============================
-- 3) Create database, schema, warehouse (as SYSADMIN)
-- ===============================
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS IDENTIFIER($database_name);
USE DATABASE IDENTIFIER($database_name);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($schema_name);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($warehouse_name)
  COMMENT = 'Warehouse used for backup operations'
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_RESUME = TRUE
  AUTO_SUSPEND = 60
  ENABLE_QUERY_ACCELERATION = TRUE
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2
  WAREHOUSE_TYPE = 'STANDARD'
  RESOURCE_CONSTRAINT = 'STANDARD_GEN_2'
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 2
  SCALING_POLICY = 'STANDARD';

-- ===============================
-- 4) Privilege grants (as SYSADMIN - schema/db owner)
-- ===============================
-- Base access to database and schema
GRANT USAGE ON DATABASE IDENTIFIER($database_name) TO ROLE IDENTIFIER($role_name);
GRANT USAGE ON SCHEMA IDENTIFIER($schema_name) TO ROLE IDENTIFIER($role_name);
GRANT ALL ON SCHEMA IDENTIFIER($schema_name) TO ROLE IDENTIFIER($role_name);

-- Warehouse access
GRANT USAGE ON WAREHOUSE IDENTIFIER($warehouse_name) TO ROLE IDENTIFIER($role_name);

-- Example: grant access to an existing data DB/Schema and specific tables
-- (Edit DATA_DB and SCH as needed or remove if not applicable)
GRANT USAGE ON DATABASE DATA_DB TO ROLE IDENTIFIER($role_name);
GRANT CREATE SCHEMA ON DATABASE DATA_DB TO ROLE IDENTIFIER($role_name);
GRANT USAGE ON SCHEMA DATA_DB.SCH TO ROLE IDENTIFIER($role_name);
GRANT ALL ON SCHEMA DATA_DB.SCH TO ROLE IDENTIFIER($role_name);
GRANT SELECT ON TABLE DATA_DB.SCH.CUSTOMER  TO ROLE IDENTIFIER($role_name);
GRANT SELECT ON TABLE DATA_DB.SCH.CUSTOMERS TO ROLE IDENTIFIER($role_name);
GRANT SELECT ON TABLE DATA_DB.SCH.SUPPLIER  TO ROLE IDENTIFIER($role_name);

-- Optional: allow the role to create databases at account level
USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE IDENTIFIER($role_name);

-- ===============================
-- 5) Switch to backup role and context
-- ===============================
USE ROLE IDENTIFIER($role_name);
USE DATABASE IDENTIFIER($database_name);
USE SCHEMA IDENTIFIER($schema_name);

-- ===============================
-- 6) Create backup policies
-- ===============================
-- Hourly backups, expire after 90 days
CREATE BACKUP POLICY IF NOT EXISTS hourly_backup_policy
  SCHEDULE = '60 MINUTE'
  EXPIRE_AFTER_DAYS = 90
  COMMENT = 'Hourly backups that expire after 90 days';

-- Daily backups with retention lock (Business Critical Edition)
-- CREATE BACKUP POLICY IF NOT EXISTS daily_backup_policy_locked
  -- WITH RETENTION LOCK
  -- SCHEDULE = '1440 MINUTE'
  -- EXPIRE_AFTER_DAYS = 90
  -- COMMENT = 'Regulatory backups: 90 days with retention lock';

-- Daily backups without retention lock
CREATE BACKUP POLICY IF NOT EXISTS daily_backup_policy
  SCHEDULE = '1440 MINUTE'
  EXPIRE_AFTER_DAYS = 90
  COMMENT = 'Regulatory backups: 90 days';

-- Twice-weekly backups using cron (Tue & Fri 23:00 UTC)
CREATE BACKUP POLICY IF NOT EXISTS twice_weekly_backup_policy
  SCHEDULE = 'USING CRON 0 23 * * 2,5 UTC'
  EXPIRE_AFTER_DAYS = 7
  COMMENT = 'Twice-weekly backups that expire after 7 days';

-- ===============================
-- 7) Create backup sets and apply policies
-- ===============================
-- Table-level backup set example
CREATE BACKUP SET IF NOT EXISTS CUSTOMER_HOUR_BACKUPS
  FOR TABLE DATA_DB.SCH.CUSTOMER
  WITH BACKUP POLICY hourly_backup_policy;

-- Schema-level backup set example
CREATE BACKUP SET IF NOT EXISTS SCHEMA_BACKUPS
  FOR SCHEMA DATA_DB.SCH
  WITH BACKUP POLICY daily_backup_policy;

-- Database-level backup set example
CREATE BACKUP SET IF NOT EXISTS DATABASE_BACKUP
  FOR DATABASE DATA_DB
  WITH BACKUP POLICY twice_weekly_backup_policy;

-- ===============================
-- 8) Manage backup sets (apply/suspend/resume)
-- ===============================
-- Apply/replace policy (use FORCE to replace existing policy)
ALTER BACKUP SET CUSTOMER_HOUR_BACKUPS APPLY BACKUP POLICY hourly_backup_policy FORCE;
ALTER BACKUP SET SCHEMA_BACKUPS       APPLY BACKUP POLICY hourly_backup_policy FORCE;
ALTER BACKUP SET DATABASE_BACKUP      APPLY BACKUP POLICY hourly_backup_policy FORCE;

-- Suspend & resume backups on a set
ALTER BACKUP SET CUSTOMER_HOUR_BACKUPS SUSPEND BACKUP POLICY;
ALTER BACKUP SET CUSTOMER_HOUR_BACKUPS RESUME BACKUP POLICY;

-- Example: drop a backup set (irreversible for the set; does not delete existing backups immediately)
-- DROP BACKUP SET CUSTOMER_HOUR_BACKUPS;


-- ===============================
-- End of script
-- ===============================
