
-- =============================================================
-- Snowflake Backup Setup & Operations Script
-- Author: Generated by M365 Copilot for Chetan Surti
-- Date: 2026-01-06
-- Purpose: Create role, database, schema, warehouse; grant privileges;
--          define backup policies; create/alter backup sets; and restore.
-- Notes:
--  * Adjust variable values below as needed before running.
--  * Some features (e.g., retention lock) require Business Critical Edition or higher.
--  * Run sections in order for best results.
-- =============================================================

-- ===============================
-- 1) Set variables (edit as needed)
-- ===============================
SET database_name  = 'BACKUP_DB';
SET schema_name    = 'BACKUP_SCM';
SET role_name      = 'BACKUP_ROLE';
SET warehouse_name = 'BACKUP_WH';

-- capture current user to grant the role later
SET current_username = (SELECT CURRENT_USER());

-- ===============================
-- 2) Inspect backup sets
-- ===============================
SHOW BACKUP SETS IN ACCOUNT;
SHOW BACKUP SETS LIKE '%_BACKUP%';
DESC BACKUP SET DATABASE_BACKUP;

-- ===============================
-- 3) Restore from backups
-- ===============================
-- Find backup IDs
SHOW BACKUPS IN BACKUP SET CUSTOMER_HOUR_BACKUPS;
SHOW BACKUPS IN BACKUP SET SCHEMA_BACKUPS;
SHOW BACKUPS IN BACKUP SET DATABASE_BACKUP;

-- Restore examples (replace IDENTIFIER values with actual backup_id from SHOW commands)
-- Restore table
CREATE TABLE DATA_DB.SCH.RESTORED_CUSTOMER
FROM BACKUP SET CUSTOMER_HOUR_BACKUPS IDENTIFIER '8cdda219-7978-4b0f-9d38-bad19aa72d94';

-- Restore schema
CREATE SCHEMA DATA_DB.RESTORED_SCH
FROM BACKUP SET SCHEMA_BACKUPS IDENTIFIER 'd768f08d-caa2-4fc5-9ac1-95787f034783';

-- Restore database
CREATE DATABASE RESTORED_DATA_DB
FROM BACKUP SET DATABASE_BACKUP IDENTIFIER '21e50707-d63f-437f-b418-db67d2953b4d';

-- ===============================
-- End of script
-- ===============================
